[part1-example1]
interpreter = "cpython-314"
code = "ff202506.py"
input_path = "example1.txt"
value = 4
solved = true
duration = 1.4098994142841548e-05
parse_duration = 4.837995220441371e-06

[part2-example1]
interpreter = "cpython-314"
code = "ff202506.py"
input_path = "example1.txt"
value = 0
solved = true
duration = 0.0012312200051383115
parse_duration = 4.837995220441371e-06

[part3-example1]
interpreter = "cpython-314"
code = "ff202506.py"
input_path = "example1.txt"
value = 1_500
solved = true
duration = 0.001582769000378903
parse_duration = 4.837995220441371e-06
