[part1-example1]
interpreter = "cpython-314"
code = "ff202503.py"
input_path = "example1.txt"
value = "10,20,30"
solved = true
duration = 3.7113997677806765e-05
parse_duration = 5.321999196894467e-06

[part2-example1]
interpreter = "cpython-314"
code = "ff202503.py"
input_path = "example1.txt"
value = 0
solved = true
duration = 2.2236999939195812e-05
parse_duration = 5.321999196894467e-06

[part3-example1]
interpreter = "cpython-314"
code = "ff202503.py"
input_path = "example1.txt"
value = 37
solved = true
duration = 1.3646997103933245e-05
parse_duration = 5.321999196894467e-06
